Repository Endermandels/Sylvia, pull requests merged in 2024-03, with the labels that each got.

#110 Add sound effects to the game (hopefully bug free this time)
  Audio Subsystem/AudioManager.gd
  Audio Subsystem/MusicPlayer.gd
  Audio Subsystem/SFXPlayer.gd
  Music/retro_funk.ogg
  Music/retro_funk.ogg.import
  Sound Effects/Menu-Selection-Change-E.ogg
  Sound Effects/Menu-Selection-Change-E.ogg.import
  Sound Effects/eating-sound-effect-36186.ogg
  Sound Effects/eating-sound-effect-36186.ogg.import
  Sound Effects/horn.ogg
  Sound Effects/horn.ogg.import
  battle/BattleScene.gd
  battle/BattleScene.tscn
  start_menu/start_menu.gd
  start_menu/start_menu.tscn
Labels: enhancement

#113 Elijah/unit tests
  Audio Subsystem/AudioManager.gd
  Audio Subsystem/AudioManager.tscn
  tests/unit/test_character.gd
Labels: enhancement

#111 Nate/enemy tests
  battle/BattleScene.tscn
  battle/Enemy.gd
  tests/unit/test_enemy.gd
Labels: enhancement

#114 Elijah/update character movement
  battle/Character.gd
  card_ui/card_ui.tscn
  tests/unit/test_audiosystem.gd
Labels: bug

#116 Daniel/unit tests
  battle_ui/food_count.tscn
  tests/unit/test_card_states.gd
  tests/unit/test_foodCounter.gd
  tests/unit/test_hearts_container.gd
Labels: enhancement

#117 Daniel/show possible moves
  battle/BattleScene.gd
  battle/BattleScene.tscn
  battle/Space.gd
  battle/Space.tscn
  card_ui/card_ui.tscn
  tests/unit/test_character.gd
Labels: enhancement

#119 Elijah/update unit tests
  tests/unit/test_character.gd
Labels: bug

#120 Elijah/finish resetting board state
  battle/BattleScene.gd
  battle/Character.gd
  battle/Space.gd
  battle/Stats.gd
  battle/food.gd
  battle_ui/food_count.gd
Labels: enhancement

#121 Add spawn_enemies function
  battle/BattleScene.gd
Labels: enhancement

#122 Daniel/show possible moves
  battle/Space.gd
Labels: enhancement

#123 Add attack sound effect.
  .DS_Store
  Audio Subsystem/AudioManager.tscn
  Audio Subsystem/MusicPlayer.gd
  Audio Subsystem/SFXPlayer.gd
  Music/.DS_Store
  Music/battle_music (surf).ogg
  Sound Effects/.DS_Store
  Sound Effects/punch.ogg
  Sound Effects/punch.ogg.import
  battle/BattleScene.gd
Labels: enhancement

#124 Emma/alt controls
  battle/BattleScene.gd
  battle/BattleScene.tscn
  project.godot
  start_menu/start_menu.gd
  ui_theme/Settings.gd
Labels: enhancement

#126 Add pause menu
  Pause Menu/pause_menu.gd
  Pause Menu/pause_menu.gdshader
  Pause Menu/pause_menu.tscn
  battle/BattleScene.gd
  battle/BattleScene.tscn
  project.godot
Labels: enhancement

#127 Elijah/refactor space script
  battle/BattleScene.gd
  battle/Space.gd
  card_ui/card_states/card_released_state.gd
Labels: bug

#129 Emma/alt controls
  addons/input_helper/InputHelper.cs
  addons/input_helper/LICENSE
  addons/input_helper/assets/update.svg
  addons/input_helper/assets/update.svg.import
  addons/input_helper/components/download_update_panel.gd
  addons/input_helper/components/download_update_panel.tscn
  addons/input_helper/input_helper.gd
  addons/input_helper/plugin.cfg
  addons/input_helper/plugin.gd
  addons/input_helper/views/download_dialog.gd
  addons/input_helper/views/download_dialog.tscn
  battle/BattleScene.gd
  project.godot
  start_menu/KeyMapScript.gd
  start_menu/start_menu.gd
  start_menu/start_menu.tscn
  tests/unit/test_accessibility.gd
Labels: enhancement

#131 Enemy can't move to player's space
  battle/Enemy.gd
Labels: bug

#132 Daniel/stop player move on top of enemy
  battle/BattleScene.gd
  battle/Space.gd
Labels: bug, enhancement
